# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fota.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from upload import upload_firmware
from PyQt5 import QtCore, QtGui, QtWidgets

# pyuic5 -x fota.ui -o fotaui.py


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 700))
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
                                 "background-color: rgb(16, 16, 16);\n"
                                 "}\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 50, 71, 41))
        self.label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                                 "color:#595959;\n"
                                 "")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 50, 81, 41))
        self.label_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                                   "color:#595959;\n"
                                   "")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(780, 50, 181, 41))
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                                   "color:#595959;\n"
                                   "")
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(760, 100, 281, 41))
        self.lineEdit_3.setStyleSheet("border: 2px solid;\n"
                                      "border-color: rgb(89, 89, 89);\n"
                                      "background-color: rgb(16, 16, 16);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 210, 81, 41))
        self.label_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                                   "color:#595959;\n"
                                   "")
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 260, 281, 41))
        self.lineEdit_4.setStyleSheet("border: 2px solid;\n"
                                      "border-color: rgb(89, 89, 89);\n"
                                      "background-color: rgb(16, 16, 16);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 210, 141, 41))
        self.label_5.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                                   "color:#595959;\n"
                                   "")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(780, 210, 41, 41))
        self.label_6.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                                   "color:#595959;\n"
                                   "")
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(400, 260, 281, 41))
        self.lineEdit_5.setStyleSheet("border: 2px solid;\n"
                                      "border-color: rgb(89, 89, 89);\n"
                                      "background-color: rgb(16, 16, 16);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(760, 260, 281, 41))
        self.lineEdit_6.setStyleSheet("border: 2px solid;\n"
                                      "border-color: rgb(89, 89, 89);\n"
                                      "background-color: rgb(16, 16, 16);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 350, 211, 41))
        self.label_7.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                                   "color:#595959;\n"
                                   "")
        self.label_7.setObjectName("label_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(50, 400, 631, 231))
        self.lineEdit_7.setStyleSheet("border: 2px solid;\n"
                                      "border-color: rgb(89, 89, 89);\n"
                                      "background-color: rgb(16, 16, 16);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(760, 400, 281, 41))
        self.lineEdit_8.setStyleSheet("border: 2px solid;\n"
                                      "border-color: rgb(89, 89, 89);\n"
                                      "background-color: rgb(16, 16, 16);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(770, 350, 121, 41))
        self.label_8.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                                   "color:#595959;\n"
                                   "")
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(830, 530, 151, 51))
        self.pushButton.setStyleSheet("background-color: rgb(0, 114, 255);\n"
                                      "border-radius: 20px;\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(50, 100, 281, 41))
        self.comboBox.setStyleSheet("border: 2px solid;\n"
                                    "selection-background-color: rgb(189, 189, 189);\n"
                                    "border-color: rgb(89, 89, 89);\n"
                                    "background-color: rgb(16, 16, 16);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(400, 100, 281, 41))
        self.comboBox_2.setStyleSheet("border: 2px solid;\n"
                                      "border-color: rgb(89, 89, 89);\n"
                                      "background-color: rgb(16, 16, 16);")
        self.comboBox_2.setObjectName("comboBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Car ID"))
        self.label_2.setText(_translate("MainWindow", "ECU ID"))
        self.label_3.setText(_translate("MainWindow", "Firmware Version"))
        self.label_4.setText(_translate("MainWindow", "Version"))
        self.label_5.setText(_translate("MainWindow", "Firmware File"))
        self.label_6.setText(_translate("MainWindow", "Key"))
        self.label_7.setText(_translate("MainWindow", "Software Description"))
        self.label_8.setText(_translate("MainWindow", "Description"))
        self.pushButton.setText(_translate("MainWindow", "Upload"))
        self.comboBox.setItemText(0, _translate("MainWindow", "A1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "A2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "A3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "A4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "A5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "A6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "A7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "A8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "A9"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
